// Enum constants for SQLite compatibility
// Since SQLite doesn't support enums, we use string constants

export const UserRole = {
  PARTICIPANT: 'PARTICIPANT',
  ORGANIZER: 'ORGANIZER',
  HOST: 'HOST',
  JUDGE: 'JUDGE',
  ADMIN: 'ADMIN',
} as const;

export const UserStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  SUSPENDED: 'SUSPENDED',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
} as const;

export const HackathonStatus = {
  DRAFT: 'DRAFT',
  PUBLISHED: 'PUBLISHED',
  REGISTRATION_OPEN: 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  IN_PROGRESS: 'IN_PROGRESS',
  SUBMISSION_OPEN: 'SUBMISSION_OPEN',
  SUBMISSION_CLOSED: 'SUBMISSION_CLOSED',
  JUDGING: 'JUDGING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const HackathonCategory = {
  WEB_DEVELOPMENT: 'WEB_DEVELOPMENT',
  MOBILE_DEVELOPMENT: 'MOBILE_DEVELOPMENT',
  AI_ML: 'AI_ML',
  BLOCKCHAIN: 'BLOCKCHAIN',
  CYBERSECURITY: 'CYBERSECURITY',
  DATA_SCIENCE: 'DATA_SCIENCE',
  GAME_DEVELOPMENT: 'GAME_DEVELOPMENT',
  IOT: 'IOT',
  OTHER: 'OTHER',
} as const;

export const SubmissionStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  UNDER_AI_REVIEW: 'UNDER_AI_REVIEW',
  AI_REVIEWED: 'AI_REVIEWED',
  NEEDS_IMPROVEMENT: 'NEEDS_IMPROVEMENT',
  PASSED_TO_OFFLINE_REVIEW: 'PASSED_TO_OFFLINE_REVIEW',
  UNDER_OFFLINE_REVIEW: 'UNDER_OFFLINE_REVIEW',
  REJECTED: 'REJECTED',
  APPROVED: 'APPROVED',
  WINNER: 'WINNER',
} as const;

export const SubmissionType = {
  INDIVIDUAL: 'INDIVIDUAL',
  TEAM: 'TEAM',
} as const;

export const TeamStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  DISBANDED: 'DISBANDED',
} as const;

export const TeamMemberRole = {
  LEADER: 'LEADER',
  MEMBER: 'MEMBER',
} as const;

export const TeamMemberStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
} as const;

export const ReviewStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
} as const;

export const NotificationType = {
  HACKATHON_PUBLISHED: 'HACKATHON_PUBLISHED',
  REGISTRATION_OPEN: 'REGISTRATION_OPEN',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  SUBMISSION_DEADLINE_APPROACHING: 'SUBMISSION_DEADLINE_APPROACHING',
  SUBMISSION_RECEIVED: 'SUBMISSION_RECEIVED',
  AI_REVIEW_COMPLETE: 'AI_REVIEW_COMPLETE',
  OFFLINE_REVIEW_ASSIGNED: 'OFFLINE_REVIEW_ASSIGNED',
  REVIEW_COMPLETE: 'REVIEW_COMPLETE',
  TEAM_INVITATION: 'TEAM_INVITATION',
  TEAM_MEMBER_JOINED: 'TEAM_MEMBER_JOINED',
  TEAM_MEMBER_LEFT: 'TEAM_MEMBER_LEFT',
  HACKATHON_WINNER: 'HACKATHON_WINNER',
  GENERAL: 'GENERAL',
} as const;

export const NotificationStatus = {
  UNREAD: 'UNREAD',
  READ: 'READ',
  ARCHIVED: 'ARCHIVED',
} as const;

export const AuditLogAction = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SUBMIT: 'SUBMIT',
  REVIEW: 'REVIEW',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  PUBLISH: 'PUBLISH',
  CANCEL: 'CANCEL',
} as const;

